version: '2'
services:
  web:
      image: 252686778722.dkr.ecr.eu-west-1.amazonaws.com/red5.ai:latest
      command: "python manage.py runserver 0.0.0.0:8000"
      ports:
        - "80:8000"
      env_file:
        - ./.env.dev
      links:
        - db
      cpu_shares: 100
      mem_limit: 262144000

  db:
      image: kartoza/postgis:11.0-2.5
      volumes:
        - postgres-data:/var/lib/postgresql/data/
      environment:
        # If you need to create multiple database you can add coma separated databases eg gis,data
        - POSTGRES_DB=red5_dev
        - POSTGRES_USER=admin
        - POSTGRES_PASS=adminadmin
        - ALLOW_IP_RANGE=0.0.0.0/0
        # Add extensions you need to be enabled by default in the DB. Default are the three specified below
        - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
      ports:
        - 5432:5432
      restart: on-failure

      cpu_shares: 100
      mem_limit: 262144000

volumes:
  postgres-data: