version: '3.3'

services:
  web:
    build: ./app
    command: gunicorn red5_web.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=red5_dev
      - POSTGRES_USER=admin
      - POSTGRES_PASS=adminadmin
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"

volumes:
  postgres-data: