version: '3.3'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: "gunicorn red5_web.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres-data: