# Generated by Django 2.2.10 on 2020-02-25 13:08

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('fullname', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('market_value', models.BigIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('fullname', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('alpha2_code', models.CharField(blank=True, max_length=2, null=True)),
                ('alpha3_code', models.CharField(blank=True, max_length=3, null=True)),
                ('numeric_code', models.IntegerField(blank=True, null=True)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='OpexItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('fullname', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Premises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('is_leasable', models.BooleanField(blank=True, null=True)),
                ('is_occupied', models.BooleanField(blank=True, null=True)),
                ('area_size', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Premises',
                'verbose_name_plural': 'Premises',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('fullname', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RentRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_start_date', models.DateField()),
                ('lease_end_date', models.DateField()),
                ('leased_area', models.FloatField()),
                ('rent', models.BigIntegerField()),
                ('leased_area_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Unit')),
                ('premises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Premises')),
                ('rent_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('fullname', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('area_size', models.FloatField(blank=True, null=True)),
                ('book_value', models.BigIntegerField(blank=True, null=True)),
                ('market_value', models.BigIntegerField(blank=True, null=True)),
                ('cadastre_value', models.BigIntegerField(blank=True, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('sale_price', models.BigIntegerField(blank=True, null=True)),
                ('cunstruction_year', models.IntegerField(blank=True, null=True)),
                ('is_profitable', models.BooleanField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('area_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Unit')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.Asset')),
                ('book_value_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Currency')),
                ('cadastre_value_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Currency')),
                ('market_value_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Currency')),
                ('sale_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Currency')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.AddField(
            model_name='premises',
            name='area_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Unit'),
        ),
        migrations.AddField(
            model_name='premises',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Property'),
        ),
        migrations.CreateModel(
            name='Microlocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Currency'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Country'),
        ),
        migrations.CreateModel(
            name='AssetOpex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('fullname', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('value', models.BigIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Asset')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Currency')),
                ('opex_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OpexItem')),
            ],
            options={
                'verbose_name': 'Asset opex',
                'verbose_name_plural': 'Assets opexes',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.City'),
        ),
        migrations.AddField(
            model_name='asset',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Country'),
        ),
        migrations.AddField(
            model_name='asset',
            name='market_value_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Currency'),
        ),
        migrations.AddField(
            model_name='asset',
            name='microlocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Microlocation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Region'),
        ),
    ]
