# Generated by Django 2.2.10 on 2020-02-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200225_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='premises',
            name='number',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
