# Generated by Django 2.2.10 on 2020-02-29 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200226_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentroll',
            name='premises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='api.Premises'),
        ),
    ]
