# Generated by Django 2.2.10 on 2020-03-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200229_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentroll',
            name='lease_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rentroll',
            name='lease_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rentroll',
            name='leased_area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rentroll',
            name='leased_area_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Unit'),
        ),
        migrations.AlterField(
            model_name='rentroll',
            name='rent',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rentroll',
            name='rent_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Currency'),
        ),
    ]
