# Generated by Django 2.2.10 on 2020-03-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200316_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='number',
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha2_code',
            field=models.CharField(blank=True, help_text='ISO2 country code', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha3_code',
            field=models.CharField(blank=True, help_text='ISO3 country code', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='ISO3 Currency code', max_length=3),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
