# Generated by Django 2.2.10 on 2020-03-17 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200317_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetopex',
            old_name='montly_value',
            new_name='monthly_value',
        ),
        migrations.RemoveField(
            model_name='assetopex',
            name='asset',
        ),
        migrations.AddField(
            model_name='assetopex',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opex_set', to='api.Property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='premises',
            name='area_size',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
